workertags:
  caasp4: suse-internal

jobs:
  deploy-k8s: false
  pre-upgrade-deploy-kubecf: true
  pre-upgrade-smoke-tests: true
  deploy-stratos: false
  upgrade-kubecf: true
  post-upgrade-smoke-tests: true
  cf-acceptance-tests-brain: true
  sync-integration-tests: true
  minibroker-integration-tests: true
  cf-acceptance-tests: true
  clean-cap: true
  destroy-kubecf: false
jobs_ordered:
- deploy-k8s
- pre-upgrade-deploy-kubecf
- pre-upgrade-smoke-tests
- deploy-stratos
- upgrade-kubecf
- post-upgrade-smoke-tests
- sync-integration-tests
- cf-acceptance-tests
- minibroker-integration-tests
- cf-acceptance-tests-brain
- clean-cap
- destroy-kubecf
backends:
  caasp4: true
  aks: false
  gke: false
  eks: false
availabilities:
  sa: true
  ha: true
  all: true
schedulers:
  diego: true
  eirini: true
catapult:
  uri: https://github.com/SUSE/catapult
  branch: master
brain:
  verbose: false
  inorder: false
  include: ""
  exclude: ""
cats:
  nodes: 6
  flake-attempts: 5
  timeout-scale: "3.0"
s3minibroker:
  bucket: minibroker-helm-charts
  region: us-east-1
  regexp: minibroker-charts/minibroker-(.*).tgz
s3:
  bucket: kubecf
  region: us-west-2
  regexp: kubecf-bundle-v0.0.0-(.*\..*).tgz
# Scheduling is required for nightly builds, enabling it removes regular trigger on kubecf bundle.
schedule:
  enabled: true
  start: 12:00 AM
  stop: 12:10 AM
  location: America/Vancouver
logs:
  enabled: false
