workertags:
  caasp4: suse-internal

jobs:
  deploy-k8s: false
  deploy-kubecf: true
  smoke-tests: true
  cf-acceptance-tests-brain: true
  sync-integration-tests: true
  minibroker-integration-tests: true
  cf-acceptance-tests: true
  upgrade-kubecf: true
  deploy-stratos: false
  destroy-kubecf: false
jobs_ordered:
- deploy-k8s
- deploy-kubecf
- smoke-tests
- sync-integration-tests
- minibroker-integration-tests
- cf-acceptance-tests
- upgrade-kubecf
- cf-acceptance-tests-brain
- deploy-stratos
- destroy-kubecf
backends:
  caasp4: true
  aks: false
  gke: false
  eks: false
availabilities:
  sa: true
  ha: true
  all: true
schedulers:
  diego: true
  eirini: true
catapult:
  uri: https://github.com/SUSE/catapult
  branch: master
brain:
  verbose: false
  inorder: false
  include: ""
  exclude: ""
cats:
  nodes: 6
  flake-attempts: 5
  timeout-scale: "3.0"
s3minibroker:
  bucket: minibroker-helm-charts
  region: us-east-1
  regexp: minibroker-charts/minibroker-(.*).tgz
s3:
  bucket: cap-release-artifacts
  regexp: CAP-(.*).tgz
  region: us-east-1
schedule:
  enabled: false
logs:
  enabled: false
