---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/base-ci
    tag: kubecf
inputs:
- name: ci
- name: s3.chart-bundle
- name: helm-charts-repo
params:
  GITHUB_TOKEN: ~
  GITHUB_PRIVATE_KEY: ~
  GIT_MAIL: ~
  GIT_USER: ~
  CHART_BUNDLE: ~
  HELM_CHARTS_REPO: ~
run:
  path: ci/cap-helm-charts-ci/tasks/create_pr.sh
