---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/binary_builder_obs_opensuse
inputs:
- name: ci
- name: s3.chart-bundle
params:
  GITHUB_TOKEN: ~
  GITHUB_PRIVATE_KEY: ~
  GIT_MAIL: ~
  GIT_USER: ~
  CHART_BUNDLE: ~
  HELM_CHARTS_REPO: ~
  OBS_USERNAME: ~
  OBS_PASSWORD: ~
run:
  path: ci/cap-sources-aggregation/tasks/push_to_obs.sh
